[build]
  publish = "."

[identity]
  registration = "invite_only"

[identity.emails]
  confirmation = false
  invite = false
  recovery = false
  email_change = false

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/post-template.html"
  status = 200

[[redirects]]
  from = "https://srisaispecialitydentalcare.in"
  to = "https://www.srisaispecialitydentalcare.in"
  status = 301
  force = true

[[redirects]]
  from = "https://srisaispecialitydentalcare.in/*"
  to = "https://www.srisaispecialitydentalcare.in/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://srisaispecialitydentalcare.in"
  to = "https://www.srisaispecialitydentalcare.in"
  status = 301
  force = true

[[redirects]]
  from = "http://srisaispecialitydentalcare.in/*"
  to = "https://www.srisaispecialitydentalcare.in/:splat"
  status = 301
  force = true
