[build]
  publish = "."

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/post-template.html"
  status = 200

[[redirects]]
  from = "/blog-admin"
  to = "/blog-admin/index.html"
  status = 200

[[redirects]]
  from = "/blog-admin/"
  to = "/blog-admin/index.html"
  status = 200

[[redirects]]
  from = "https://srisaispecialitydentalcare.in"
  to = "https://www.srisaispecialitydentalcare.in"
  status = 301
  force = true

[[redirects]]
  from = "https://srisaispecialitydentalcare.in/*"
  to = "https://www.srisaispecialitydentalcare.in/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://srisaispecialitydentalcare.in"
  to = "https://www.srisaispecialitydentalcare.in"
  status = 301
  force = true

[[redirects]]
  from = "http://srisaispecialitydentalcare.in/*"
  to = "https://www.srisaispecialitydentalcare.in/:splat"
  status = 301
  force = true
