backend:
  name: github
  repo: sambasivabat12-debug/testing-sri-sai-speciality-dental-care-
  branch: main

media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Dr. T. Venkat Rao" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Dental Tips"
          - "Oral Health"
          - "Root Canal Treatment"
          - "Dental Implants"
          - "Dental Braces"
          - "Dental Aligners"
          - "Wisdom Tooth Removal"
          - "Dental Fillings"
          - "Teeth Whitening Treatment"
          - "Dental Bridges"
          - "Dental Dentures"
          - "Dental Crown"
          - "Smile Makeover"
          - "Children's Dentistry"
          - "Clinic News"
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "string", required: false }
      - { label: "Published", name: "draft", widget: "boolean", default: false }
